# Generated by Django 3.2.4 on 2021-07-14 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('Codigo', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='CodigoJuego')),
                ('NombreDelJuego', models.CharField(max_length=50, verbose_name='NombreDeljuego')),
                ('CompañiaCreadora', models.CharField(max_length=50, verbose_name='CompañiaCreadora')),
                ('Plataforma', models.CharField(blank=True, max_length=50, null=True, verbose_name='Plataforma')),
                ('Descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripcion')),
                ('Caratula', models.ImageField(null=True, upload_to='Caratulas')),
                ('Categorias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categorias')),
            ],
        ),
        migrations.CreateModel(
            name='MundoAbierto',
            fields=[
                ('Codigo', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='CodigoJuego')),
                ('NombreDelJuego', models.CharField(max_length=50, verbose_name='NombreDeljuego')),
                ('CompañiaCreadora', models.CharField(max_length=50, verbose_name='CompañiaCreadora')),
                ('Plataforma', models.CharField(blank=True, max_length=50, null=True, verbose_name='Plataforma')),
                ('Descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripcion')),
                ('Caratula', models.ImageField(null=True, upload_to='Caratulas')),
                ('Categorias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categorias')),
            ],
        ),
        migrations.CreateModel(
            name='Lucha',
            fields=[
                ('Codigo', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='CodigoJuego')),
                ('NombreDelJuego', models.CharField(max_length=50, verbose_name='NombreDeljuego')),
                ('CompañiaCreadora', models.CharField(max_length=50, verbose_name='CompañiaCreadora')),
                ('Plataforma', models.CharField(blank=True, max_length=50, null=True, verbose_name='Plataforma')),
                ('Descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripcion')),
                ('Caratula', models.ImageField(null=True, upload_to='Caratulas')),
                ('Categorias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categorias')),
            ],
        ),
        migrations.CreateModel(
            name='Aventura',
            fields=[
                ('Codigo', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='CodigoJuego')),
                ('NombreDelJuego', models.CharField(max_length=50, verbose_name='NombreDeljuego')),
                ('CompañiaCreadora', models.CharField(max_length=50, verbose_name='CompañiaCreadora')),
                ('Plataforma', models.CharField(blank=True, max_length=50, null=True, verbose_name='Plataforma')),
                ('Descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripcion')),
                ('Caratula', models.ImageField(null=True, upload_to='Caratulas')),
                ('Categorias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categorias')),
            ],
        ),
    ]
